### PR TITLE
Support GHC 8.2 and 8.0

### LINKED ISSUE #126: doctest doesn't work for 8.2
I get 

```
Preprocessing test suite 'graphql-api-doctests' for graphql-api-0.2.0..
Building test suite 'graphql-api-doctests' for graphql-api-0.2.0..

tests/Spec.hs:1:8: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘Spec’
  |
1 | module Main
  |        ^^^^
```

for

```
$ ghc --version 
The Glorious Glasgow Haskell Compilation System, version 8.2.1
```

### LINKED ISSUE #156: Officially support ghc 8.2 and 8.0.2+
Official support means:

- [ ] explicitly stating what we support
- [ ] updating our CI to run both 8.0.2 and 8.2

This means something like stackage LTS 9.21 and 10.4. I have no idea what this means in terms of CircleCI config or changes to `stack.yaml`.

Triggered by #126

### PR DESCRIPTION
**Pull request by jml**
Fixes #156. Also fixes #126. 

Currently depends on #159.

### CODE REVIEW

**Comment by jml** [comment]
Not sure what to do about CircleCI not returning status.

**Comment by teh** [comment]
Did you try this: https://circleci.com/docs/2.0/workflows-waiting-status/ ? That suggests it's circle 1.0 config leftover problem. Not sure otherwise..

**Comment by jml** [comment]
Thanks! This will be much easier to review now that #159 is merged.

**Comment by jml** [comment]
@teh PTAL

**Pull request merged**
